framework:
    cache:
        # Use Redis as the default cache adapter
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_DSN)%'
        
        # Define a cache pool for the application
        pools:
            app.cache:
                adapter: cache.adapter.redis
                provider: cache.default_redis_provider
                default_lifetime: 3600
        
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaced cache keys.
        prefix_seed: symfony_sponsorship/cache
