framework:
  messenger:
    # Enable failure transport for async messages
    failure_transport: failed

    transports:
      # Sync transport for messages that must be handled immediately
      sync: "sync://"

      # Async transport for background processing
      async: "%env(MESSENGER_TRANSPORT_DSN)%"

      # Failed messages transport
      failed: "doctrine://default?queue_name=failed"

    default_bus: messenger.bus.default

    buses:
      messenger.bus.default:
        default_middleware: allow_no_handlers

    routing:
      # Route all messages to async transport by default
      # You can specify specific message classes to route to sync if needed
      # Example: 'App\Message\UrgentMessage': sync
      "*": async
