framework:
    messenger:
        # Disable failure transport for now
        # failure_transport: failed

        transports:
            # Use sync transport for simplicity
            sync: 'sync://'
            # failed: 'doctrine://default?queue_name=failed'


        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                default_middleware: allow_no_handlers

        routing:
            # Route all messages to sync transport
            '*': sync
