framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(resolve:REDIS_DSN)%'

    # Configuration for Redis Messenger transport
    messenger:
        transports:
            async_redis: '%env(resolve:REDIS_DSN)%/messages'
