name: CI

on:
  push:
    branches: [main, dev, "feat/*"]
  pull_request:
    branches: [main, dev]

jobs:
  tests:
    name: Run tests on MySQL
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: symfony_sponsorship_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

      mailpit:
        image: axllent/mailpit:latest
        ports:
          - 1025:1025
          - 8025:8025

    strategy:
      matrix:
        php: ["8.2", "8.3"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer:v2
          extensions: intl, pdo_mysql, zip, gd, exif, pcntl, bcmath, opcache, redis

      - name: Validate composer.json
        run: composer validate --strict

      - name: Get Composer cache dir
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --prefer-dist --no-progress --no-interaction

      - name: Set up environment
        run: |
          cp .env.test .env
          echo "DATABASE_URL=mysql://test_user:test_password@127.0.0.1:3306/symfony_sponsorship_test?serverVersion=8.0&charset=utf8mb4" >> .env
          echo "MAILER_DSN=smtp://localhost:1025" >> .env
          echo "REDIS_DSN=redis://127.0.0.1:6379" >> .env
          echo "MESSENGER_TRANSPORT_DSN=redis://127.0.0.1:6379/messages" >> .env

      - name: Create & migrate database
        run: |
          php bin/console doctrine:database:create --if-not-exists --env=test
          php bin/console doctrine:migrations:migrate --no-interaction --env=test

      - name: Lint YAML
        run: php bin/console lint:yaml config/

      - name: Lint Twig
        run: php bin/console lint:twig templates/

      - name: Lint Container
        run: php bin/console lint:container

      - name: Run PHPUnit
        run: php bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml
          fail_ci_if_error: false

      - name: Static analysis (PHPStan)
        run: vendor/bin/phpstan analyse -l max src

      - name: CS Fixer (dry-run)
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Security check (Roave Security Advisories)
        run: |
          composer require --dev roave/security-advisories:^1.0 --no-update
          composer update --lock
          # Si ce job échoue, c'est qu'une vulnérabilité est détectée dans composer.lock.
